# Generated by Django 4.1.3 on 2022-11-09 02:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_alter_todo_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='created_timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='todo',
            name='modified_timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
